### ISSUE TITLE
Visualization Suggestions

### ISSUE THREAD

**Issue by jvolden** [Anti-Rona-Task-Force/COVID#2]
Add your visualization suggestions and information here.

**Comment by beabout** [comment]
### US Map Plotting (by State and by County)
[Geographical Plotting: Plotly and Choropleth](https://towardsdatascience.com/intro-to-geographical-plotting-237f59fec735)

**Comment by BaileySri** [comment]
County level map plotting with heat map example from Plotly documentation:
https://plotly.com/python/county-choropleth/
Slider to represent time evolution of data over State level map plotting
https://amaral.northwestern.edu/blog/step-step-how-plot-map-slider-represent-time-evolu
