### ISSUE TITLE
Anomaly Detection

### ISSUE THREAD

**Issue by beabout** [Anti-Rona-Task-Force/COVID#8]
description and details for the Anomaly Detection portion of the project here.

**Comment by beabout** [comment]
- [ ] Grab data & combine data sets to include Deaths/Cases Per Capita

**Comment by bpramann1** [comment]
Grab the census data for each county and combine it with the COVID\data\raw\covid-19-data\us-counties.csv data. Create a per capita column for cases that is cases dived by pop in the county. Do the same for deaths.

**Comment by bpramann1** [comment]
Create a small snapshot of the data by filtering the data by one day

**Comment by bpramann1** [comment]
For each topic cases and deaths, create histograms by binning the per capita data and then counting the number of counties that have a per capita in a bin range. Compare the histogram created against common probability distributions to see if it looks like the sample data might have come from a population that follows a probability distribution. If it looks like a pdf( probability density function), we will use that to model the data and find anomalies. If not, we will not be able to use classical approaches.
